version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: ../src/server
    container_name: rss-server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    depends_on:
      - mongo
    volumes:
      - ../src/server:/app

  client:
    build:
      context: ../src/client
    container_name: rss-client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server
    volumes:
      - ../src/client:/app

volumes:
  mongo-data:
